target-version = "py310"
line-length = 88
exclude = [
    ".venv",
    "venv",
    "env",
    "alembic",
    ".git",
]


[lint]
extend-select = ["E501", "ARG001", "ARG002", "ARG003", "ARG004", "RUF100"]

[extend-per-file-ignores]
"__init__.py" = ["F401"]
